### PR TITLE
Update Travis config for GHC-8.8

### PR DESCRIPTION
**Pull request by sjakobi**

### CODE REVIEW

**Comment by conal** [comment]
Thanks again!

**Comment by conal** [comment]
@sjakobi: I haven't used checkers myself in quite a while, and I'd be happy to hand it off to another caring and qualified maintainer. You've made many commits, and I like your sensibilities. Interested in taking checkers from here?

**Comment by conal** [comment]
No hurry for an answer, and please feel free to decline. Being responsible for a relatively popular package gives me some exposure to perspectives I might otherwise miss in maintaining packages that are of more interest to me and less interest to others.

**Comment by sjakobi** [comment]
Thanks for the offer @conal, but I'd prefer to remain a simple contributor. I currently don't expect to use `checkers` a lot in the future, and there are lot of parts in `checkers` that I don't really understand and would make it difficult for me to "own" the package.

Do feel free though to ping me when issues come up! So far I've much enjoyed contributing here. :)

**Comment by conal** [comment]
I understand. Thanks for considering and for your contributions!

**Pull request merged**
