### PR TITLE
Add selective checkers

### PR DESCRIPTION
**Pull request by isovector**
This PR adds checkers for the `Selective` class. Doing so incurs a package dependency, but it is tiny and depends on no non-core libraries.

### CODE REVIEW

**Comment by isovector** [comment]
With thanks to @masadeedu

**Comment by sjakobi** [comment]
While the Travis status reporting doesn't work, you can find the CI results here:

https://travis-ci.org/github/conal/checkers/pull_requests

Apparently `selective` doesn't build with GHC 7.10 because it claims to require `TypeApplications`. I don't see that it actually uses `TypeApplications` in the library, so maybe that can be fixed.

@conal Could you review too?

**Comment by isovector** [comment]
The compatibility issue should be fixed now.

**Comment by sjakobi** [comment]
Thanks!

I think the merge conflict is preventing Travis from building the PR.

**Comment by isovector** [comment]
resolved

**Comment by conal** [comment]
Thanks for the help. Is the `stack.yaml.lock` file addition accidental?

**Comment by isovector** [comment]
Yeah, it was accidental. Nice catch! Removed now.

**Comment by conal** [comment]
> Merge attempt failed
> Head branch was modified. Review and try the merge again.

Hm. I've not run into this message before.

**Comment by sjakobi** [comment]
> The compatibility issue should be fixed now.

Apparently `selective` still doesn't build with GHC 7.10: https://travis-ci.org/github/conal/checkers/jobs/705603779

**Comment by isovector** [comment]
ugh. sorry about this. can you guys work on getting CI reattached to github, and I'll go get this sorted out? my bad on the churn here.

**Comment by sjakobi** [comment]
> can you guys work on getting CI reattached to github

Yeah, I opened https://github.com/conal/checkers/issues/52 about this. @conal, could you take a look?

@isovector Have you possibly run into similar issues with Travis in other projects? How did you fix it?

**Comment by sjakobi** [comment]
Any updates on the GHC 7.10 compatibility @isovector?

**Comment by isovector** [comment]
It fell off my radar --- the thing I want isn't a selective functor after all. Did you get CI working? Doing that for `selective` seems like the easiest path forward.

**Comment by sjakobi** [comment]
> Did you get CI working? Doing that for `selective` seems like the easiest path forward.

Yep. See #52 or https://github.com/quchen/prettyprinter/issues/172.

**Comment by sjakobi** [comment]
@isovector Have you reported the issue at least? Would you prefer me to revert this PR? Please don't leave us hanging with broken CI.

**Comment by isovector** [comment]
Please revert this. I've run out of bandwidth on this issue. You might want
to get in touch with @snowleopard to move forward!

**Pull request merged**
