### PR TITLE
Generic instances

### PR DESCRIPTION
**Pull request by isovector**
This PR adds support for generically deriving `EqProp` instances; and uses it to give instances for the most of the types in `base`.

### CODE REVIEW

**Comment by conal** [comment]
Thanks, @isovector! I like the look of this contribution. I don't have the personal bandwidth right now to test, and I see that CI is failing. For which GHC versions have you tested? Are you able to multi-version-CI-test on your fork? Any suggestions how to proceed?

**Comment by isovector** [comment]
CI is now green :) There's a bit of nonsense CPP to deal with all of the insane versions of base, but I tried to keep it to a minimum.

**Comment by conal** [comment]
Thanks, @isovector!

**Comment by conal** [comment]
I bumped the version number for release to Hackage and am getting the following error:
```
bash-3.2$ cabal clean
bash-3.2$ cabal install
Wrote tarball sdist to
/Users/conal/Haskell/checkers/dist-newstyle/sdist/checkers-0.5.5.tar.gz
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] next goal: checkers (user goal)
[__0] rejecting: checkers-0.5.5 (constraint from user target requires ==0.5.4)
[__0] rejecting: checkers-0.5.4, checkers-0.5.2, checkers-0.5.1,
checkers-0.5.0, checkers-0.4.14, checkers-0.4.13, checkers-0.4.11,
checkers-0.4.10, checkers-0.4.9.5, checkers-0.4.9.4, checkers-0.4.9.3,
checkers-0.4.9.2, checkers-0.4.9, checkers-0.4.8, checkers-0.4.7,
checkers-0.4.6, checkers-0.4.5, checkers-0.4.4, checkers-0.4.3,
checkers-0.4.2, checkers-0.4.1, checkers-0.4.0, checkers-0.3.2,
checkers-0.3.1, checkers-0.3.0, checkers-0.2.9, checkers-0.2.8,
checkers-0.2.7, checkers-0.2.6, checkers-0.2.5, checkers-0.2.4,
checkers-0.2.3, checkers-0.2.2, checkers-0.2, checkers-0.1.4, checkers-0.1.3,
checkers-0.1.2, checkers-0.1.1, checkers-0.1 (constraint from user target
requires ==0.5.5)
[__0] fail (backjumping, conflict set: checkers)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: checkers

bash-3.2$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.6.5
bash-3.2$ cabal --version
cabal-install version 3.0.0.0
compiled using version 3.0.0.0 of the Cabal library 
bash-3.2$ 
```

@isovector Do you know what's going on here?

**Comment by isovector** [comment]
No idea, sorry! Opaque errors like these are the reason I use stack.

**Comment by conal** [comment]
I searched for this error message and found [a relevant Q\&A](https://github.com/haskell/cabal/issues/5818#issuecomment-450530491). In my case, \~/.ghc/x86\_64-darwin-8.6.5/environments/default contained the following line:

    package-id chckrs-0.5.4-db0ab588

No idea why “chckrs” instead of “checkers”. Deleting this line seems to fix the problem.

**Comment by conal** [comment]
[Released.](http://hackage.haskell.org/package/checkers-0.5.5).

**Pull request merged**
